### ISSUE TITLE
Request: Same channel ranked/unranked queues

### ISSUE THREAD

**Issue by darkshade9** [aq2world/PUBobot2#6]
Right now only queues in a different channel can be non-ranked and take rating data from another channel. Could it be implemented that queues in the same channel be non-ranked but take rating from another queue in the same channel?

This would help us in the way that pickup games are played 4v4-5v5. If there are more than 10 participants signed up we start "chaos games" instead. Due to the high number of participants it turns out to a completely different style of game play and unfortunately messes up the ranks for the pickup games. Having both queues in the same channel, but one un-ranked that composes teams by rank would be appreciated by many in our community!

**Comment by anzejarni** [comment]
This functionality is already possible with existing code by setting:
ranked = False
pick_teams = 'matchmaking'
rating_channel = {empty if same channel} | 'some_other_channel'
